---
- name: Destroy Droplet
  community.digitalocean.digital_ocean_droplet:
    state: absent
    oauth_token: "{{DO_API_TOKEN}}"
    id: "{{ lookup('csvfile', inventory_hostname + ' file=droplet_list.csv delimiter=,') | default('') }}"
  register: my_droplet

- name: Record Droplet to file
  lineinfile:
    path: droplet_list.csv
    regexp: "^{{inventory_hostname}}.*"   
    state: absent
    create: true
   
- name: Update A record for www based on name/type/data
  community.digitalocean.digital_ocean_domain_record:
    state: absent
    oauth_token: "{{DO_API_TOKEN}}"
    domain: fogcity.de
    ttl: 36
    type: A
    name: "{{inventory_hostname.split('.')[0] | lower }}"
